// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// f2_blocks_from_Relate
NumericVector f2_blocks_from_Relate(SEXP file_anc, SEXP file_mut, SEXP poplabels, SEXP file_map, Nullable<CharacterVector> chrs, Nullable<double> blgsize, Nullable<double> mu, Nullable<double> tmin, Nullable<double> t, Nullable<int> transitions, Nullable<int> use_muts, Nullable<int> minMAF, SEXP dump_blockpos, Nullable<int> apply_corr);
RcppExport SEXP _twigstats_f2_blocks_from_Relate(SEXP file_ancSEXP, SEXP file_mutSEXP, SEXP poplabelsSEXP, SEXP file_mapSEXP, SEXP chrsSEXP, SEXP blgsizeSEXP, SEXP muSEXP, SEXP tminSEXP, SEXP tSEXP, SEXP transitionsSEXP, SEXP use_mutsSEXP, SEXP minMAFSEXP, SEXP dump_blockposSEXP, SEXP apply_corrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type file_anc(file_ancSEXP);
    Rcpp::traits::input_parameter< SEXP >::type file_mut(file_mutSEXP);
    Rcpp::traits::input_parameter< SEXP >::type poplabels(poplabelsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type file_map(file_mapSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type chrs(chrsSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type blgsize(blgsizeSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type t(tSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type transitions(transitionsSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type use_muts(use_mutsSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type minMAF(minMAFSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dump_blockpos(dump_blockposSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type apply_corr(apply_corrSEXP);
    rcpp_result_gen = Rcpp::wrap(f2_blocks_from_Relate(file_anc, file_mut, poplabels, file_map, chrs, blgsize, mu, tmin, t, transitions, use_muts, minMAF, dump_blockpos, apply_corr));
    return rcpp_result_gen;
END_RCPP
}
// f2_blocks_from_RelateAges
NumericVector f2_blocks_from_RelateAges(SEXP pref, SEXP file_mut, Nullable<double> blgsize, Nullable<int> transitions, Nullable<double> maxmiss, Nullable<StringVector> fam, Nullable<StringVector> pops, Nullable<StringVector> chrs, Nullable<double> tmin, Nullable<double> t, Nullable<int> include_undated, Nullable<int> minMAF, Nullable<int> apply_corr, Nullable<int> debug_mode);
RcppExport SEXP _twigstats_f2_blocks_from_RelateAges(SEXP prefSEXP, SEXP file_mutSEXP, SEXP blgsizeSEXP, SEXP transitionsSEXP, SEXP maxmissSEXP, SEXP famSEXP, SEXP popsSEXP, SEXP chrsSEXP, SEXP tminSEXP, SEXP tSEXP, SEXP include_undatedSEXP, SEXP minMAFSEXP, SEXP apply_corrSEXP, SEXP debug_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pref(prefSEXP);
    Rcpp::traits::input_parameter< SEXP >::type file_mut(file_mutSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type blgsize(blgsizeSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type transitions(transitionsSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type maxmiss(maxmissSEXP);
    Rcpp::traits::input_parameter< Nullable<StringVector> >::type fam(famSEXP);
    Rcpp::traits::input_parameter< Nullable<StringVector> >::type pops(popsSEXP);
    Rcpp::traits::input_parameter< Nullable<StringVector> >::type chrs(chrsSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type t(tSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type include_undated(include_undatedSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type minMAF(minMAFSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type apply_corr(apply_corrSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type debug_mode(debug_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(f2_blocks_from_RelateAges(pref, file_mut, blgsize, transitions, maxmiss, fam, pops, chrs, tmin, t, include_undated, minMAF, apply_corr, debug_mode));
    return rcpp_result_gen;
END_RCPP
}
// Painting
void Painting(SEXP file_anc, SEXP file_mut, SEXP file_map, SEXP file_out, SEXP poplabels, Nullable<double> blgsize, Nullable<StringVector> pops, Nullable<CharacterVector> chrs);
RcppExport SEXP _twigstats_Painting(SEXP file_ancSEXP, SEXP file_mutSEXP, SEXP file_mapSEXP, SEXP file_outSEXP, SEXP poplabelsSEXP, SEXP blgsizeSEXP, SEXP popsSEXP, SEXP chrsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type file_anc(file_ancSEXP);
    Rcpp::traits::input_parameter< SEXP >::type file_mut(file_mutSEXP);
    Rcpp::traits::input_parameter< SEXP >::type file_map(file_mapSEXP);
    Rcpp::traits::input_parameter< SEXP >::type file_out(file_outSEXP);
    Rcpp::traits::input_parameter< SEXP >::type poplabels(poplabelsSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type blgsize(blgsizeSEXP);
    Rcpp::traits::input_parameter< Nullable<StringVector> >::type pops(popsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type chrs(chrsSEXP);
    Painting(file_anc, file_mut, file_map, file_out, poplabels, blgsize, pops, chrs);
    return R_NilValue;
END_RCPP
}
// ExpPaintingProfile
NumericVector ExpPaintingProfile(SEXP file_anc, SEXP file_mut, SEXP poplabels, Nullable<StringVector> pops, Nullable<CharacterVector> chrs);
RcppExport SEXP _twigstats_ExpPaintingProfile(SEXP file_ancSEXP, SEXP file_mutSEXP, SEXP poplabelsSEXP, SEXP popsSEXP, SEXP chrsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type file_anc(file_ancSEXP);
    Rcpp::traits::input_parameter< SEXP >::type file_mut(file_mutSEXP);
    Rcpp::traits::input_parameter< SEXP >::type poplabels(poplabelsSEXP);
    Rcpp::traits::input_parameter< Nullable<StringVector> >::type pops(popsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type chrs(chrsSEXP);
    rcpp_result_gen = Rcpp::wrap(ExpPaintingProfile(file_anc, file_mut, poplabels, pops, chrs));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_twigstats_f2_blocks_from_Relate", (DL_FUNC) &_twigstats_f2_blocks_from_Relate, 14},
    {"_twigstats_f2_blocks_from_RelateAges", (DL_FUNC) &_twigstats_f2_blocks_from_RelateAges, 14},
    {"_twigstats_Painting", (DL_FUNC) &_twigstats_Painting, 8},
    {"_twigstats_ExpPaintingProfile", (DL_FUNC) &_twigstats_ExpPaintingProfile, 5},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_twigstats(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
